const HARVESTER_BODY = [WORK, WORK, MOVE];
const HAULER_BODY = [CARRY, CARRY, MOVE, MOVE];
const UPGRADER_BODY = [WORK, CARRY, MOVE];

module.exports = {
    HARVESTER_BODY,
    HAULER_BODY,
    UPGRADER_BODY
};
