const Profiler = require('../utils/profiler');
const { wrapModuleFunctions } = require('../utils/moduleWrapper');
const { executeManager } = require('../utils/errorHandler');
const eventBus = require('../os/eventBus');
const {
    EVENT_HOSTILE_SPOTTED,
    EVENT_CONSTRUCTION_STARTED,
    EVENT_STRUCTURE_DECAY
} = require('../constants/eventTypes');

/**
 * @file RemoteIntelManager.js
 * @description Dedicated manager for collecting, storing, and providing intel on remote rooms.
 */

class RemoteIntelManager {
    constructor() {
        this.initialized = false;
    }

    /**
     * Initializes the manager, setting up event subscriptions.
     */
    init() {
        if (this.initialized) return;

        eventBus.subscribe(EVENT_HOSTILE_SPOTTED, this.handleHostileSpotted.bind(this));
        eventBus.subscribe(EVENT_CONSTRUCTION_STARTED, this.handleConstructionStarted.bind(this));
        eventBus.subscribe(EVENT_STRUCTURE_DECAY, this.handleStructureDecay.bind(this));

        this.initialized = true;
    }

    /**
     * Main run loop for the manager.
     */
    run() {
        this.init();
        // Periodic tasks can be added here if needed
    }

    /**
     * Handle hostile spotted events.
     * @param {Object} data - The event data containing roomName and event details.
     */
    handleHostileSpotted(data) {
        if (!data || !data.roomName) return;
        this._ensureIntelMap();

        let remoteData = global.State.remoteIntel.get(data.roomName);
        if (!remoteData) remoteData = new Map();

        remoteData.set('lastHostileActivity', Game.time);
        // Hostile presence may temporarily invalidate a room as a remote candidate
        remoteData.set('hasActiveThreat', true);

        global.State.remoteIntel.set(data.roomName, remoteData);
    }

    /**
     * Handle construction started events.
     * @param {Object} data - The event data containing roomName.
     */
    handleConstructionStarted(data) {
        if (!data || !data.roomName) return;
        this._ensureIntelMap();

        let remoteData = global.State.remoteIntel.get(data.roomName);
        if (!remoteData) remoteData = new Map();

        remoteData.set('lastConstructionActivity', Game.time);

        global.State.remoteIntel.set(data.roomName, remoteData);
    }

    /**
     * Handle structure decay events.
     * @param {Object} data - The event data containing roomName.
     */
    handleStructureDecay(data) {
        if (!data || !data.roomName) return;
        this._ensureIntelMap();

        let remoteData = global.State.remoteIntel.get(data.roomName);
        if (!remoteData) remoteData = new Map();

        remoteData.set('lastDecayActivity', Game.time);

        // We could theoretically mark infrastructure as needing repair here,
        // but for intel purposes we mostly just want to know when it happens

        global.State.remoteIntel.set(data.roomName, remoteData);
    }

    /**
     * Ensures the global intel map exists.
     * @private
     */
    _ensureIntelMap() {
        if (!global.State) return;
        if (!global.State.remoteIntel) {
            global.State.remoteIntel = new Map();
        }
    }

    /**
     * Processes and stores an intel report from a scout or event.
     * This supplements the standard intel manager by focusing on remote progression details.
     * @param {string} roomName - The name of the room to process.
     */
    processScoutReport(roomName) {
        this._ensureIntelMap();
        if (!global.State.remoteIntel) return;

        // Fetch basic intel generated by the primary intel manager
        let basicIntel = null;
        if (global.State.intel && global.State.intel.has(roomName)) {
            basicIntel = global.State.intel.get(roomName);
        }

        let remoteData = global.State.remoteIntel.get(roomName);
        if (!remoteData) remoteData = new Map();

        remoteData.set('lastUpdate', Game.time);

        // Sync critical data for quick O(1) access
        if (basicIntel) {
            remoteData.set('hostile', basicIntel.hostile || false);
            remoteData.set('owner', basicIntel.owner || null);
            remoteData.set('reservation', basicIntel.reservation || null);
            remoteData.set('sources', basicIntel.sources || 0);
            remoteData.set('mineral', basicIntel.mineral || null);
            remoteData.set('type', basicIntel.type || 'unknown');
            remoteData.set('level', basicIntel.level || 0);
            remoteData.set('towerCount', basicIntel.towerCount || 0);
            remoteData.set('spawnCount', basicIntel.spawnCount || 0);
            remoteData.set('remoteCandidate', basicIntel.remoteCandidate || false);
            remoteData.set('expansionScore', basicIntel.expansionScore || 0);
        }

        global.State.remoteIntel.set(roomName, remoteData);
    }

    /**
     * Retrieves stored intel for a specific room.
     * @param {string} roomName - The room name.
     * @returns {Map<string, any>|null} The intel object, or null if not found.
     */
    getIntel(roomName) {
        if (!global.State || !global.State.remoteIntel) return null;
        return global.State.remoteIntel.get(roomName) || null;
    }

    /**
     * Identifies potential remote mining rooms based on intel.
     * @returns {Array<string>} An array of room names suitable for remote mining.
     */
    getPotentialRemoteMiningRooms() {
        if (!global.State || !global.State.remoteIntel) return [];

        const candidates = [];
        for (const [roomName, data] of global.State.remoteIntel.entries()) {
            if (data.get('remoteCandidate')) {
                candidates.push(roomName);
            }
        }
        return candidates;
    }

    /**
     * Identifies potential expansion targets based on intel, sorted by score.
     * @returns {Array<Object>} An array of objects containing roomName and score.
     */
    getExpansionTargets() {
        if (!global.State || !global.State.remoteIntel) return [];

        const targets = [];
        for (const [roomName, data] of global.State.remoteIntel.entries()) {
            const expansionScore = data.get('expansionScore');
            if (expansionScore && expansionScore > 0) {
                targets.push({ roomName, score: expansionScore });
            }
        }

        // Sort descending by score
        targets.sort((a, b) => b.score - a.score);
        return targets;
    }
}

const instance = new RemoteIntelManager();

// Export the instance and a run function wrapped with Profiler
const exportedRun = Profiler.wrap('RemoteIntelManager', function() {
    instance.run();
});

module.exports = {
    run: wrapModuleFunctions(exportedRun, (funcName, originalFunc, ...args) => executeManager(`RemoteIntelManager.${funcName}`, originalFunc, ...args)),
    processScoutReport: instance.processScoutReport.bind(instance),
    getIntel: instance.getIntel.bind(instance),
    getPotentialRemoteMiningRooms: instance.getPotentialRemoteMiningRooms.bind(instance),
    getExpansionTargets: instance.getExpansionTargets.bind(instance),
    // Export instance for direct access if needed, mainly tests
    instance
};
